---
# tasks file for nginx
- name: Installing packages epel repo
  package:
    name: "epel-release"
    state: "installed"

- name: Installing packages for nginx
  package:
    name: "nginx"
    state: "installed"

- name: copying template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: disable selinux
  selinux:
    state: "disabled"


- name: service start
  service:
    name: "nginx"
    state: "started"


